// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      pkg: grunt.file.readJSON('package.json'),
      coffee: {
        build: {
          expand: true,
          cwd: 'app/static/dev/coffee',
          src: ['**/*.coffee'],
          dest: 'app/static/dev/js',
          ext: '.js'
        }
      },
      sass: {
        dist: {
          files: [
            {
              expand: true,
              cwd: "public/scss",
              src: ['**/*.scss'],
              dest: 'public/css',
              ext: '.css'
            }
          ]
        }
      },
      watch: {
        options: {
          livereload: true
        },
        scripts: {
          files: ['**/*.coffee', 'Gruntfile.coffee'],
          tasks: ["coffee", "uglify"],
          option: {
            spawn: false
          }
        },
        css: {
          files: ['**/*.scss'],
          tasks: ["sass"],
          option: {
            spawn: false
          }
        }
      },
      uglify: {
        build: {
          expand: true,
          cwd: 'app/static/dev/js',
          src: '**/*.js',
          dest: 'app/static/js',
          ext: ".min.js"
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-coffee');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-contrib-sass');
    grunt.loadNpmTasks("grunt-contrib-uglify");
    grunt.registerTask("default", function() {
      return grunt.task.run(["coffee", "sass", "watch"]);
    });
    grunt.registerTask("build", ['coffee', 'sass', "watch"]);
    return grunt.registerTask("compress", ["uglify"]);
  };

}).call(this);
