"""empty message

Revision ID: 23357ff5b064
Revises: 49de6917161f
Create Date: 2014-07-27 15:06:20.223925

"""

# revision identifiers, used by Alembic.
revision = '23357ff5b064'
down_revision = '49de6917161f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
