"""empty message

Revision ID: 239d7de182ae
Revises: None
Create Date: 2014-07-29 16:16:44.075517

"""

# revision identifiers, used by Alembic.
revision = '239d7de182ae'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_address'), 'address', ['address'], unique=True)
    op.create_table('actualmeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('availableNumber', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('mealID', sa.Integer(), nullable=True),
    sa.Column('addressId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['addressId'], ['address.id'], ),
    sa.ForeignKeyConstraint(['mealID'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mealID')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phoneNumber', sa.String(length=13), nullable=False),
    sa.Column('nickName', sa.String(length=12), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('addressId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['addressId'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phoneNumber'), 'users', ['phoneNumber'], unique=True)
    op.create_table('pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('mealId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mealId'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('mealId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mealId'], ['meals.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.phoneNumber'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('pictures')
    op.drop_index(op.f('ix_users_phoneNumber'), table_name='users')
    op.drop_table('users')
    op.drop_table('actualmeals')
    op.drop_index(op.f('ix_address_address'), table_name='address')
    op.drop_table('address')
    op.drop_table('meals')
    ### end Alembic commands ###
