"""empty message

Revision ID: 26b924811c08
Revises: 23357ff5b064
Create Date: 2014-07-27 21:26:45.082346

"""

# revision identifiers, used by Alembic.
revision = '26b924811c08'
down_revision = '23357ff5b064'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('name', sa.String(length=32), nullable=True))
    op.drop_column('pictures', 'url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('url', sa.VARCHAR(length=32), nullable=True))
    op.drop_column('pictures', 'name')
    ### end Alembic commands ###
