"""empty message

Revision ID: 2740485b22e8
Revises: None
Create Date: 2014-07-30 11:19:05.054520

"""

# revision identifiers, used by Alembic.
revision = '2740485b22e8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
