"""empty message

Revision ID: 454a000f9965
Revises: None
Create Date: 2014-07-29 20:46:30.675226

"""

# revision identifiers, used by Alembic.
revision = '454a000f9965'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
