"""empty message

Revision ID: 51a8c329fad2
Revises: None
Create Date: 2014-07-28 17:16:46.343145

"""

# revision identifiers, used by Alembic.
revision = '51a8c329fad2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
